language: node_js
node_js:
  - '6'
before_install:
  - openssl aes-256-cbc -K $encrypted_1ac08c44deb2_key -iv $encrypted_1ac08c44deb2_iv
    -in id_rsa.enc -out id_rsa -d
before_script:
  - bundle install --without development
script:
  - bundle exec rake
  - bundle exec jekyll build
  - npm run gh-pages-travis
env:
  global:
  - GIT_NAME="Peter Halliday"
  - GIT_EMAIL="pghalliday@gmail.com"
  - DEPLOY_BRANCH="deploy"
  - TARGET_BRANCH="master"
  - SOURCE_DIR="_site"
