name: pghalliday
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: rouge
excerpt_separator: "\n"
exclude: [
  README.md,
  Guardfile,
  Gemfile,
  Gemfile.lock,
  bower.json,
  package.json,
  node_modules,
  npm-debug.log,
  id_rsa.enc
]
