name: pghalliday
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
excerpt_separator: "\n"
exclude: [
  README.md,
  Rakefile,
  Gemfile,
  Gemfile.lock
]
