name: pghalliday
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
excerpt_separator: "\n"
exclude: [
  README.md,
  Rakefile,
  Gemfile,
  Gemfile.lock,
  bower.json,
  package.json,
  node_modules,
  aliases.sh,
  npm-debug.log,
  bower_components,
  gulpfile.js,
  deploy_key.enc,
  deploy.sh
]
