name: pghalliday
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: rouge
excerpt_separator: "\n"
exclude: [
  README.md,
  Guardfile,
  Rakefile,
  lib,
  Gemfile,
  Gemfile.lock,
  bower.json,
  bower_components,
  id_rsa.enc,
  id_rsa
]
